---
title: "Curso Reinforcement Learning"
author: "Jazmín  Sarahí Flores Gómez"
format: html
editor: visual
---

## Introducción

## Línea del tiempo
```{r}
library(bibtex)
## Activate the Core Packages

library(tidyverse) ## Brings in a core of useful functions
```

```{r}
library(gt)        ## Tables
## Specific packages
library(milestones)
## Initialize defaults
## Initialize defaults
column <- lolli_styles()

data <- read_csv(col_names=TRUE, show_col_types=FALSE, file='rl_time_line.csv')
```

```{r}
## Sort the table by date
data <- data |>
  arrange(date)

## Build a table
gt(data) |>
  #cols_hide(columns = event) |>
  tab_style(cell_text(v_align = "top"),
            locations = cells_body(columns = date)) |>
  tab_source_note(source_note = "Source: Sutton and Barto (2018)") 
```

```{r}
## Adjust some defaults
column$color <- "pink"
column$size  <- 15
column$source_info <- "Source: Sutton and Barto (2018)"

## Milestones timeline
milestones(datatable = data, styles = column)
```


## Tarea 2